apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: "mysql-service"
  replicas: 3 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "1500m" 
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
